language: android

before_install:
  - chmod +x gradlew
  - echo yes | sdkmanager "build-tools;27.0.1"

jdk: oraclejdk8
android:
  components:
    - tools  
    - platform-tools
    - build-tools-27.0.3
    - android-27
    - extra-android-m2repository 
    - $ANDROID_TARGET
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8
    - ANDROID_TARGET=android-27
    - ANDROID_ABI=armeabi-v7a

script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedCheck
  
notifications:
  email:
    - angelocaporaso03@gmail.com
    - upcovino@gmail.com
  on_success: change
  on_failure: always
