language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - build-tools-27.0.3
    - android-27
script:
  - ./gradlew connectedCheck
  
notifications:
  email:
    - angelocaporaso03@gmail.com
    - upcovino@gmail.com
  on_success: change
  on_failure: always
