language: android

before_install:
 - chmod +x gradlew

jdk: oraclejdk8
android:
  components:
    - tools
    - build-tools-27.0.3
    - android-27

notifications:
  email:
    - angelocaporaso03@gmail.com
    - upcovino@gmail.com
  on_success: change
  on_failure: always
