language: android

before_install:
  - chmod +x gradlew
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

jdk: oraclejdk8
android:
  components:
    - tools
    - build-tools-27.0.3
    - android-27

notifications:
  email:
    - angelocaporaso03@gmail.com
    - upcovino@gmail.com
  on_success: change
  on_failure: always
