language: android

before_install:
  - chmod +x gradlew
  - echo yes | sdkmanager "build-tools;27.0.1"

jdk: oraclejdk8
android:
  components:
    - tools
    - build-tools-27.0.3
    - android-27

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

notifications:
  email:
    - angelocaporaso03@gmail.com
    - upcovino@gmail.com
  on_success: change
  on_failure: always
